version: "3"

services:
  api:
    build: .
    ports:
      - 8000:8000

  postgres:
    image: postgres:14.5-alpine
    restart: always
    environment:
      POSTGRES_DB: imdb_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123456
    ports:
      - 5432:5432
