version: "3"

services:
  api:
    build: .
    environment:
      - POSTGRES_DB_URI=postgresql://user:123456@postgres:5432/imdb_db
    ports:
      - 8000:8000
    depends_on:
      - postgres

  postgres:
    image: postgres:14.5-alpine
    restart: always
    environment:
      POSTGRES_DB: imdb_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123456
    ports:
      - 5432:5432
